spring:
  application:
    name: Zuul-gateway

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

zuul:
  routes:
    account-service:
      path: /account/**
      service-id: account