# =======================================
# Gateway-service Server Configuration
# =======================================

# --- Spring Config
spring:
  application:
    name: gateway-service

server:
  port: 8762

# Eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

zuul:
  routes:
  ## So, if request is "/user/v1/user/tedkim", user service will get "/v1/user/tedkim".
    account-service:
      path: /account/**
      service-id: account